### ISSUE TITLE
how to using ODMS dataset

### ISSUE THREAD

**Issue by MIracleyin** [griffbr/ODMS#3]
hi, have a good day.
I hava a question.could i convert other object detection dataset to ODMS dataset.
I want to do some applications research.

**Comment by griffbr** [comment]
Hi Miracle Yin,

Thanks for your question! 

My best advice would be to convert the ODMD bounding boxes to box-shaped segmentation masks to be compatible with ODMS. That is, if you had a bounding box with image coordinates x1, x2, y1, y2, simply create a mask such that all x, y pixels x1 < x < x2, y1 < y < y2 are part of the object segmentation. Since ODMD bounding boxes are normalized (see Equation 10 of our [paper](https://arxiv.org/abs/2103.01468)), I would convert them to a binary mask image size of 480x640 to be consistent with HSR's gripper camera.

Hope this helps!

Best,
Brent

**Comment by MIracleyin** [comment]
thanks a lot. your  research give me a lot of idea.
